server:
  port: 8081
  undertow:
    threads:
      #IO线程数 一般设置为cpu核数
      io: 4
      #工作线程数  一般就是 IO * 8
      worker: 32
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 1000
    max-headers: 200
    max-parameters: 200
    max-cookies: 200
    accesslog:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
    context-path: /lining/wonder

spring:
  application:
    name: lining-wonder
  servlet:
    multipart:
      #Max file size.
      max-file-size: 50MB
      #Max request size.
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: debug